# Generated by Django 4.2 on 2023-06-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtospeech',
            name='chapter_url',
            field=models.CharField(max_length=100),
        ),
    ]
